ABHISHEK-AMRUTE/CP_Algorithms_hacktoberfest

C++/CeaserCipherAlgo

An implementation of  Ceaser Cipher Cryptography algorithm.

CeaserCipher

---

C++/dijkstra_algorithm.cpp

@ABHISHEK-AMRUTE sir,
Added one one of the most important greedy algorithm, i.e., Dijkstra's Algorithm.
#1 
Kindly review it and merge the file with the main branch if it looks OK.

Added Dijkstra's Algorithm

---

C++/String Anagram

Checking if two string are anagram of each other or not.

anagram.cpp

---

C++/Sliding_Window_algo.txt

I have added Sliding WIndow Algo in C++. Please merge it

Added Sliding_Window_algo

---

C++/linear_search.cpp

Hello sir,
Just wanted to added a code on linear searching algorithm to your repository. please kindly accept my PR .
Thank You

linear_searching

---

Sort in C++ Standard Template Library

Sort in C++ Standard Template Library

---

C++/BinaryTree_LevelOrder_Traversal.cpp

@ABHISHEK-AMRUTE  please review my pull request

BinaryTree level order Traversal in cpp

---

C++/BinaryTree/BinaryTree_LevelOrder_Traversal.cpp
C++/Queue/QueueUsingArray.cpp

@ABHISHEK-AMRUTE  please review the pull request.

Queue Using Array

---

Doubly Linked List (DLL) of Employee Data

a. Create a DLL of N Employees Data by using end insertion.
b. Display the status of DLL and count the number of nodes in it
c. Perform Insertion and Deletion at End of DLL
d. Perform Insertion and Deletion at Front of DLL
e. Demonstrate how this DLL can be used as Double Ended Queue
f. Exit

Doubly Linked List (DLL) of Employee Data

---

Operations on Strings

a. Read a Main String (STR), a Pattern String (PAT) and a Replace String (REP).
b. Perform Pattern Matching Operation: Find and Replace all occurrences of PAT in STR with
REP if PAT exists in STR. Repost suitable messages in case PAT does not exist in STR.
Support the program with functions for each of the above operations. Don’t use built-in functions.

Operations on Strings

---

g Tower of Hanoi problem with n disks

you can apply this easy code practically.

Solving Tower of Hanoi problem with n disks

---

C++/dutch_National_Flag_Algo

Desc: Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.
Here, we will use the integers 0, 1, and 2 to represent the color red, white, and blue respectively.
This algorithm helps to arrange 0s,1s,2s in an array in just O(n) time complexity and O(1) Extra space. This is the most optimal solution.

dutch_National_Flag_Algorithm

---

C++/Fibonacci_DP.cpp
C++/Z-algorithm.cpp

@ABHISHEK-AMRUTE  please review the pull request.

added Fibonacci of the number in cpp

---

C++/Z-algorithm.cpp

@ABHISHEK-AMRUTE  please review the pull request.

 add Z-algorithm in cpp

---

C++/KaratsubaAlgorithm.cpp

In this algorithm, Multiplication of two binary number occurs using Divide and Conquer approach(Karatsuba Algorithm)

Karatsuba Algorithm

---

Area of a polygon

Area of a polygon using  shoelace formula .This formula usually using  in CP Algorithm.

 Area of a polygon

---

C++/Euclid_Algorithm.cpp

Used to find the Greatest Common Divisor (GCD) of two integers.

Euclidean Algorithm

---

C++/doublehashing.cpp

The above cpp program gives detailed study of double hashing

doublehashing.cpp

---

Finding Power of Factorial Divisor

Finding Power of Factorial Divisor With Prime K

Finding Power of Factorial Divisor

---

Finding the largest zero submatrix

Finding the largest zero submatrix ,we calculate the following auxiliary matrix: d[i][j], nearest row that has a  a[i][j].

Finding the largest zero submatrix

---

Deleting from a data structure

Deleting from a data structure in O(T(n)logn)

Deleting from a data structure

---

Determinant using Kraut method

Determinant using Kraut method in O(N3)

Determinant using Kraut method

---

MPM algorithm

MPM algorithm With Maximum Flow Implementation

MPM algorithm

---

Dinic's algorithm

Dinic's algorithm With Maximum Flow Implementation

Dinic's algorithm

---

Push-relabel algorithm

Push-relabel algorithm with Maximum Flow

Push-relabel algorithm

---

Edmonds-Karp algorithm

Edmonds-Karp algorithm with implementation Maximum flow

Edmonds-Karp algorithm

---

C++/Prime_Factorization.cpp

The program used to calculate the Prime factors of a given number.

Prime Factorization C++ Program

---

connected components in a graph

connected components in a graph

connected components in a graph

---

Finding Bridges Online

Finding Bridges Online of an Undirected Graph

Finding Bridges Online

---

Strong Orientation

Strong Orientation with undirected graph is an assignment of a direction to each edge that makes it a strongly connected graph

Strong Orientation

---

Eulerian path

Finding the Eulerian path in O(M)

Eulerian path

---

C++/Longest Common subsequence.cpp

I have added a DP solution for finding the longest common subsequence in c++, could you please merge it?
thanks in advance

adding DP algorithm

---

Integration by Simpson's formula

Integration by Simpson's formula

Integration by Simpson's formula

---

Newton's method for finding roots

Newton's method for finding roots .Implementation was easy

Newton's method for finding roots

---

Sieve of Eratosthenes

Sieve of Eratosthenes with easy and triky code .and i send the implementation code

Sieve of Eratosthenes

---

C++/LCS.cpp

Created LCS

---

C++/Search in 2D matrix

Added a new problem (Search in 2D matrix) and its solution

Create Search in 2D matrix

---

C++/catalan.cpp

catalan.cpp

---

C++/Floyd_Warshall_Algorithm .cpp

The Floyd Warshall Algorithm is for solving the All Pairs Shortest Path problem. The problem is to find shortest distances between every pair of vertices in a given edge weighted directed Graph.

Create Floyd_Warshall_Algorithm .cpp

---

C++/Rotate bits of a number.cpp

#1 
Add Rotate bits of a number.cpp

Add Rotate bits of a number.cpp

---

C++/RangeMinimumQuery_SparseTable.cpp

Added the RangeMinimumQuery_SparseTable.cpp file in the C++ folder.

Added Range Minimum Query algorithm

---

C++/double link list.cpp

A doubly linked list program in c++

Added a doubly linked list program

---

C++/LinkedList/inserting a node at nth position

Hello
I am writing an algorithm to insert a node at nth position in the linked list. please check and merge it.
Thank you in advance.

 Inserting a node at nth position in a linked list

---

Array operations

a. Creating an Array of N Integer Elements
b. Display of Array Elements with Suitable Headings
c. Inserting an Element (ELEM) at a given valid Position (POS)
d. Deleting an Element at a given valid Position(POS)
e. Exit.

Array Operations

---

C++/WheelFactorizationAlgo.cpp

added Wheel factorization algorithm

added Wheel factorization algorithm

---

C++/bubblesort.cpp
C++/insertionsort.cpp
C++/selectionsort.cpp

C++ Sorting Algos with graphical representation(Command line) where you can see the working of algorithm on each step.
* Bubble Sort
* Insertion Sort
* Selection Sort

Contributing CPP sorting algorithm

---

Java/FindPair.java

Added FindPair Code in java. 
Which returns a boolean on whether a pair of given value exists or not.
Given a list of numbers and a number k, 
return whether any two numbers from the list add up to k.
For example, given [10, 15, 3, 7] and k of 17, return true since 10 + 7 is 17.

Added FindPair Code - Java

---

C++/Iterative_merge_sort.cpp

I have created a file named Iterative merge sort so as to contribute a unique sort program

Iterative Merge Sort

---

C++/BFS.cpp

Hacktoberfest

---

JavaScript/binExponentiation.js

binExponentiation returns the value raised to its power in **O(log n)** time complexity.
It even works for **-ve** powers too.

Added binExponentiation Code - Js

---

C++/Bridges_In_A_Graph_Algorithm.cpp

Please merge My pull request.
Thank you

Bridge_In_a_Graph_Algorithm

---

Insertion sort.cpp

please accept my pull request for Hacktoberfest2021

Insertion Sort

---

C++/DP/Equal Subset Sum.cpp

Equal Subset Sum code using knapsack dynamic programming in cpp.

Create Equal Subset Sum.cpp
